### ISSUE TITLE
Update tuture object to latest tuture.yml spec

### ISSUE THREAD

**Issue by mRcfps** [tutureproject/renderer#58]
The latest [spec](https://github.com/tutureproject/tuture/blob/master/docs/TUTURE_YML_SPEC.md).

Example:

```yaml
name: Name of this tutorial
language: en-US
version: 0.0.1
topics:
  - Topic A
  - Topic B
description: This is my first tutorial, come and read it!
maintainer: maintainer@example.com
steps:
  - name: Message of commit ae05546
    commit: ae05546
    explain:
      pre: Introduction placed at the top of this step
      post: Sumup placed at the bottom of this step
    diff:
      - file: Changed file A
        section:
          start: 1
          end: 10
        explain: Introduction before doing something to this part of A
      - file: Changed file A
        section:
          start: 11
          end: 20
        explain: Introduction before doing something to this part of A
      - file: Changed file B
        explain:
          pre: Introduction before doing something to B
          post: Explanation after doing something to B
  - name: Message of commit ae05546
    commit: a45bec1
    explain:
      pre: Introduction placed at the top of this step
      post: Sumup placed at the bottom of this step
    diff:
      - file: Changed file A
        explain:
          pre: Introduction before doing something to A
          post: Explanation after doing something to A
      - file: Changed file B
        explain: Introduction before doing something to B
      - file: Changed file C
        explain:
          pre: Introduction before doing something to C
          post: Explanation after doing something to C
```
